# Generated by Django 5.0.7 on 2025-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='inventory_released',
            field=models.BooleanField(default=False),
        ),
    ]
