# Generated by Django 5.0.7 on 2025-10-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_update_medio_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level_group',
            field=models.CharField(choices=[('BASICO', '1 a 8 Basico'), ('MEDIO_1_2', '1 y 2 Medio'), ('MEDIO_3_4', '3 y 4 Medio')], default='BASICO', max_length=20),
        ),
    ]
